name: Deploy Vue App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Execute Deployment Script on Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"
            [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"
            nvm use v22.15.0 || { echo "Failed to switch node version"; exit 1; }

            SERVER_PROJECT_PATH="/root/projects/Shotmeld-web"
            NGINX_WEB_ROOT="/var/www/shotmeld-web"

            echo "Navigating to project directory on server..."
            cd $SERVER_PROJECT_PATH || { echo "Failed to change directory: $SERVER_PROJECT_PATH"; exit 1; }

            echo "Pulling latest code from Git..."
            git fetch origin main || { echo "Failed to fetch latest code"; exit 1; }
            git reset --hard origin/main || { echo "Failed to reset to latest code"; exit 1; }

            echo "Installing dependencies on server..."
            yarn install --force || { echo "Failed to install dependencies"; exit 1; }

            echo "Building project on server..."
            yarn build || { echo "Failed to build project"; exit 1; }

            echo "Deploying built files to Nginx web root..."
            sudo mkdir -p $NGINX_WEB_ROOT
            sudo chown www-data:www-data $NGINX_WEB_ROOT || { echo "Failed to set initial ownership for web root"; exit 1; }
            sudo chmod 755 $NGINX_WEB_ROOT || { echo "Failed to set initial permissions for web root"; exit 1; }

            sudo cp -rp ./dist/* $NGINX_WEB_ROOT/ || { echo "Failed to copy files from ./dist to $NGINX_WEB_ROOT"; exit 1; }

            sudo chown -R www-data:www-data $NGINX_WEB_ROOT || { echo "Failed to set ownership for copied files"; exit 1; }
            sudo chmod -R 755 $NGINX_WEB_ROOT || { echo "Failed to set permissions for copied files"; exit 1; }

            echo "Reloading Nginx to serve new files..."
            sudo systemctl reload nginx || { echo "Failed to reload Nginx"; exit 1; }
            echo "Deployment complete."